version: '3.8'
services:
  fullstack_app:
    build:
      context: . 
      dockerfile: dockerfile
    container_name: fullstack_app
    ports:
      - "3000:3000"
      - "5000:5000"
    networks:
      - app-net
  postgres:
    image:  postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net: {}
