name: PyLinter

on: [pull,push]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: checks out code
      - uses: actions/checkout@v3

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle 

      - name: Run pycodestyle (PEP8)
        run: |
          pycodestyle . --count --max-line-length=100 --statistics