name: PyLinter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install autopep8
        run: |
          pip install autopep8

      - name: Check code formatting with autopep8
        run: |
          autopep8 . --recursive --diff --exit-code